import type { SharedProps } from '@/types';

/**
 * Mirrors the props shared by App\Http\Middleware\HandleInertiaRequests.
 */
export const sharedProps: SharedProps = {
    locale: {
        current: 'ru',
        bcp47: 'ru-RU',
        fallback: 'ru',
        available: [
            { value: 'tj', label: 'Тоҷикӣ' },
            { value: 'ru', label: 'Русский' },
            { value: 'en', label: 'English' },
        ],
    },
    displayTimezone: 'Asia/Dushanbe',
    translations: {
        brand_name: 'Портал экологического мониторинга',
        brand_tagline: 'Официальные гидрометеорологические данные и качество воздуха',
        language_label: 'Язык',
        main_navigation: 'Основная навигация',
        nav_home: 'Станции',
        nav_silam: 'Прогноз SILAM',
        content_back: 'Назад к станциям',
        content_published_at: 'Опубликовано',
        content_type_page: 'Информационная страница',
        content_type_news: 'Новость',
        content_type_bulletin: 'Бюллетень',
        content_type_health_advice: 'Рекомендация по здоровью',
        home_heading: 'Портал экологического мониторинга Таджикистана',
        home_intro: 'Портал публикует наблюдения станций.',
        home_foundation_badge: 'Фаза 1 — основание приложения',
        home_public_preview_badge: 'Публичный обзор станций',
        mock_data_badge: 'Искусственные данные',
        mock_data_notice: 'Это вымышленные данные для разработки.',
        overview_label: 'Сводка наблюдений по стране',
        overview_stations: 'Видимые станции',
        overview_reporting: 'Станции с показаниями',
        overview_last_observation: 'Последнее наблюдение',
        not_available: 'Нет данных',
        station_map_heading: 'Станции и последние показания',
        station_map_intro: 'Выберите точку на карте.',
        station_map_label: 'Интерактивная карта станций мониторинга',
        station_no_measurements: 'Нет измерений, доступных для публикации.',
        station_view_details: 'Подробнее о станции',
        station_empty_heading: 'Данные станций ещё не загружены',
        station_empty_body: 'Обзор появится после импорта данных.',
        station_status_active: 'Работает',
        station_status_maintenance: 'Обслуживание',
        station_status_offline: 'Не в сети',
        measurement_quality_valid: 'Корректное',
        measurement_quality_suspect: 'Сомнительное',
        measurement_quality_missing: 'Нет значения',
        measurement_quality_corrected: 'Исправлено источником',
        station_back: 'Назад ко всем станциям',
        station_detail_badge: 'Наблюдения станции',
        station_metadata_heading: 'Сведения о станции',
        station_location_heading: 'Расположение',
        station_source_heading: 'Источник и работа',
        station_region: 'Регион',
        station_district: 'Район',
        station_coordinates: 'Координаты',
        station_elevation: 'Высота',
        unit_metres: 'м',
        station_type: 'Тип станции',
        station_type_air_quality: 'Качество воздуха',
        station_type_meteorological: 'Метеорологическая',
        station_type_combined: 'Комбинированная',
        station_source: 'Источник данных',
        station_last_sync: 'Последняя успешная синхронизация',
        station_not_synchronized: 'Завершённых синхронизаций пока нет',
        station_charts_heading: 'Исторические наблюдения',
        station_quality_notice: 'Невалидные показания исключены.',
        station_export_csv: 'Скачать CSV',
        station_period_heading: 'Период',
        period_24h: '24 часа',
        period_7d: '7 дней',
        period_30d: '30 дней',
        period_1y: '1 год',
        station_parameters_label: 'Параметры',
        station_all_parameters: 'Все параметры',
        station_range_label: 'Показанный период',
        station_aggregation_raw: 'Исходные наблюдения',
        station_aggregation_hour: 'Средние по часу',
        station_aggregation_day: 'Средние по дню',
        station_chart_empty: 'Нет значений.',
        station_chart_aria: 'График для :parameter, единица :unit.',
        station_corrected_points: 'Исправленных точек: :count',
        station_export_note: 'Формат CSV предварительный.',
        home_integration_status_heading: 'Состояние интеграций',
        home_integration_status_intro: 'Включаются отдельно.',
        integration_alerts_body: 'Реализовано и проверено на искусственных данных.',
        integration_silam_body: 'Уже доступно на отдельной странице.',
        silam_forecast_badge: 'Внешний модельный прогноз',
        silam_heading: 'Прогноз качества воздуха SILAM',
        silam_intro: 'Эта страница показывает модельный прогноз.',
        silam_open_external: 'Открыть SILAM в новой вкладке',
        silam_frame_region: 'Встроенный прогноз SILAM',
        silam_frame_title: 'Прогноз SILAM для Таджикистана',
        silam_fallback: 'Если прогноз недоступен, используйте внешнюю ссылку.',
        home_roadmap_heading: 'Разделы портала',
        home_roadmap_intro: 'Эти разделы подключаются позже.',
        roadmap_map: 'Карта станций и текущие значения',
        roadmap_charts: 'Графики и экспорт CSV',
        integration_alerts_heading: 'Официальные предупреждения',
        integration_silam_heading: 'Прогноз качества воздуха SILAM',
        integration_status_available: 'Доступно',
        integration_status_fixture_backed: 'На искусственных данных',
        roadmap_status: 'Планируется',
        time_timezone_notice: 'Время отображается в часовом поясе :timezone.',
        time_generated_at: 'Страница сформирована',
        footer_source: 'Официальный источник производственных данных: Гидромет',
        footer_note: 'Портал не эксплуатирует измерительное оборудование.',
        alerts_heading: 'Действующие официальные предупреждения',
        alerts_intro:
            'Предупреждения, опубликованные источником: они показаны на карте станций и перечислены ниже. Портал не выпускает собственных предупреждений.',
        alerts_mock_notice:
            'Это вымышленные демонстрационные предупреждения. Они не являются официальными, и по ним нельзя принимать решения.',
        alerts_empty_heading: 'Действующих предупреждений нет',
        alerts_empty_body:
            'Сейчас по стране ничего не опубликовано. Истёкшие и отменённые предупреждения остаются доступны в истории.',
        alert_legend_label: 'Уровень опасности',
        alert_legend_provisional:
            'Цвета — предварительный выбор портала, а не утверждённая национальная шкала опасности.',
        alert_severity_extreme: 'Чрезвычайный',
        alert_severity_severe: 'Высокий',
        alert_severity_moderate: 'Умеренный',
        alert_severity_minor: 'Низкий',
        alert_severity_unknown: 'Уровень не указан',
        alert_effective_from: 'Действует с',
        alert_expires_at: 'Действует до',
        alert_areas_label: 'Затронутые районы',
        alert_areas_none: 'Не указано',
        alert_sender: 'Отправитель',
        alert_back: 'Назад к обзору',
        alert_history_link: 'Все опубликованные предупреждения',
        alert_history_title: 'Опубликованные предупреждения',
        alert_history_intro: 'Все предупреждения, опубликованные источником.',
        alert_history_empty: 'Портал пока не опубликовал ни одного предупреждения.',
        alert_history_older: 'Более ранние предупреждения',
        alert_history_newer: 'Более поздние предупреждения',
        alert_state_in_force: 'Действует',
        alert_state_ended: 'Больше не действует',
        alert_state_withdrawn: 'Отменено',
        alert_urgency: 'Срочность',
        alert_certainty: 'Достоверность',
        alert_history_heading: 'История сообщений',
        alert_state_expired: 'Это предупреждение больше не действует. Срок истёк :time.',
        alert_state_superseded:
            'Это предупреждение больше не является текущим. Его заменило более новое сообщение :time.',
        alert_message_type_alert: 'Предупреждение',
        alert_message_type_update: 'Обновление',
        alert_message_type_cancel: 'Отмена',
        alert_message_type_ack: 'Подтверждение',
        alert_message_type_error: 'Ошибка',
        alert_urgency_immediate: 'Немедленная',
        alert_urgency_expected: 'Ожидаемая',
        alert_urgency_future: 'Отложенная',
        alert_urgency_past: 'Прошедшая',
        alert_urgency_unknown: 'Неизвестна',
        alert_certainty_observed: 'Наблюдается',
        alert_certainty_likely: 'Вероятно',
        alert_certainty_possible: 'Возможно',
        alert_certainty_unlikely: 'Маловероятно',
        alert_certainty_unknown: 'Неизвестна',
    },
};
